import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"bcd-acquisition-"));
process.env.AUTOPILOT_DB_PATH=path.join(temp,"test.sqlite"); process.env.SEED_TEST_INSTALLER="false";
const {openDatabase}=await import("../src/db");
const {acquireFromBytes}=await import("../src/ahjFormAuto");
const {loadStoredTemplates,fillLoadedForm,resolveSource}=await import("../src/ahjForms");
const {extractLabels}=await import("../src/formTextLayer");
const {bcd5952Template}=await import("../src/bcd5952Template");
const db=await openDatabase();
try {
 const bytes=fs.readFileSync("backend/test/fixtures/bcd-5952-2024.pdf");
 const llm=new Proxy({}, {get(){throw new Error("Known template must not call a model");}}) as never;
 const input={ahj:"Fixture Town",state:"OR",formType:"electrical_application",formName:"Electrical and Building Application",bytes,sourceUrl:"https://www.oregon.gov/bcd/Formslibrary/5952.pdf"};
 const result=await acquireFromBytes(db,llm,input); assert.equal(result.status,"acquired");
 const row=db.get<{id:string;form_type:string;field_map:string}>("SELECT id, form_type, field_map FROM ahj_form_templates WHERE ahj_name = ?",[input.ahj])!;
 assert.equal(row.form_type,"solar_checklist");
 const template=loadStoredTemplates(db,input.ahj,"OR")[0];
 const snapshot={snow:20,wind:"C",deadLoad:2,lightFrame:"yes",moduleMake:"Example",moduleModel:"Model A"};
 const project={id:"fixture",homeownerName:"Test Owner",ahj:input.ahj,city:"Fixture",zip:"97000",projectAddress:"1 Test Way",parserSnapshot:snapshot};
 const out=path.join(temp,"filled.pdf");
 await fillLoadedForm(template.def,bytes,{project,client:{},snapshot} as never,out);
 const labels=await extractLabels(fs.readFileSync(out)); assert.ok(labels.some(i=>i.str==="Test Owner"));
 assert.ok(labels.some(i=>i.str===input.ahj), "AcroForm supplemental department overlay must render");
 const contractorContext={project,client:{installerCompanyName:"Fixture Contractor"},snapshot} as never;
 assert.equal(resolveSource("computed.installerRole",contractorContext),"contractor");
 assert.equal(resolveSource("computed.installerRole",{project,client:{},snapshot} as never),"");
 assert.equal(resolveSource("computed.installerRole",{project,client:{installerCompanyName:"Fixture Contractor"},snapshot:{...snapshot,installerRole:"owner"}} as never),"owner");
 assert.equal(template.def.checkboxes?.Contractor.equals,"contractor");
 assert.equal(labels.filter(i=>i.str==="X").length,4);
 const map={...JSON.parse(row.field_map),verified:true};
 db.run("UPDATE ahj_form_templates SET field_map = ? WHERE id = ?",[JSON.stringify(map),row.id]);
 assert.equal((await acquireFromBytes(db,llm,input)).status,"exists");
 assert.equal(db.get<{field_map:string}>("SELECT field_map FROM ahj_form_templates WHERE id = ?",[row.id])!.field_map,JSON.stringify(map));
 assert.equal(bcd5952Template(Buffer.concat([bytes,Buffer.from("changed")]),input.sourceUrl),null);
 console.log("bcdAcquisition: actual bytes select checklist, model-free fill, verified protection, changed-byte refusal passed");
} finally { db.close(); assert.equal(path.dirname(temp),os.tmpdir()); fs.rmSync(temp,{recursive:true,force:true}); }
