// A DOCUMENT THAT CANNOT BE MISTAKEN FOR A REAL ONE.
//
// The replay benchmark files a real application on a live utility portal, and a solar
// interconnection form asks for a one-line drawing and a site plan. Leaving them blank left
// the upload path — a genuine part of "is this filing complete" — unmeasured, and capped
// every run below the rung that requires a whole filing.
//
// So the benchmark attaches this instead: a single page that says what it is in the largest
// type on it, names the run, and carries no engineering content whatsoever. Three properties
// matter and none of them are decoration:
//
//   • It is OBVIOUSLY not a plan set, to anyone who opens it for any reason.
//   • It contains no customer data — the benchmark project is fictional, and this carries
//     less than that: a title, a date, and a sentence.
//   • It is generated fresh per run rather than committed, so it can never drift into
//     looking like a fixture someone might reuse for a real filing.
//
// It goes on a draft named "ZZTest Replay Benchmark" that is never submitted and that the
// operator discards.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

/**
 * Write a clearly-marked placeholder PDF and return its path.
 *
 * @param label which slot this stands in for ("one-line drawing", "site plan") — printed on
 *              the page so a reviewer glancing at an attachment list can see what it replaced.
 */
export async function writeBenchmarkPlaceholderDoc(label: string, stamp: string): Promise<string> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]); // US Letter, the size every AHJ portal expects
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const body = await doc.embedFont(StandardFonts.Helvetica);
  const red = rgb(0.75, 0.1, 0.1);

  page.drawText("NOT A REAL DOCUMENT", { x: 54, y: 690, size: 34, font: bold, color: red });
  page.drawText("AUTOMATED BENCHMARK PLACEHOLDER", { x: 54, y: 652, size: 18, font: bold, color: red });

  const lines = [
    "",
    `Stands in for: ${label}`,
    "",
    "This page was generated by the replay benchmark, which exercises a recorded",
    "portal recipe against a live portal to measure whether it still files correctly.",
    "",
    "It contains no engineering content, no customer information, and no design of",
    "any kind. The application it is attached to is a test draft under the name",
    '"ZZTest Replay Benchmark". It is never submitted and no fee is ever paid.',
    "",
    "If you are reading this on a real submission, something has gone wrong:",
    "please discard the draft and tell the operator.",
    "",
    `Generated ${stamp}`,
  ];
  let y = 610;
  for (const line of lines) {
    if (line) page.drawText(line, { x: 54, y, size: 11, font: body, color: rgb(0.15, 0.15, 0.15) });
    y -= 18;
  }
  // A diagonal watermark, so the page reads as a placeholder even as a thumbnail.
  page.drawText("BENCHMARK", { x: 96, y: 300, size: 72, font: bold, color: rgb(0.93, 0.93, 0.93), rotate: { type: "degrees", angle: 32 } as never });

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "zz-benchmark-doc-"));
  const file = path.join(dir, `ZZTEST-BENCHMARK-PLACEHOLDER-${label.replace(/[^a-z0-9]+/gi, "-")}.pdf`);
  fs.writeFileSync(file, await doc.save());
  return file;
}
